---
# title: "Creating Reproducible Environments with Nix for Scientific Computing"
# author:
#   - Kuffour Morphy^[University of Connecticut, morphy.kuffour@uconn.edu]
# date: "`r format(Sys.Date(), '%d %B %Y')`"
bibliography: ./bib/refs.bib
output:
  bookdown::pdf_book:
    includes:
      in_header: ./preamble.tex
      before_body: ./titlepage.tex
    number_sections: yes
    keep_tex: true
    toc: false
    fig_caption: true
indent: true
# classoption: twocolumn
link-citations: yes
html_document:
    toc: false
header-includes:
  - \usepackage{amsmath}
sansfont: JetBrains Mono
mainfont: Times New Roman
urlcolor: blue
---

<!-- Start the redaction on a new page -->
<!-- \newpage -->

<!-- Start page numbering where the redaction starts -->
\pagenumbering{arabic}

```{r globaloptions, include=FALSE}
# Include here chunk options
```

```{r packages, include=FALSE}
# Load here the packages
library(reticulate)
use_python("/etc/profiles/per-user/morp/bin/python")
```

<!-- Call the child documents -->
<!-- ```{r body, child = c('01-Intro.Rmd', '02-Literature.Rmd', '03-Data-and-method.Rmd', '04-Results.Rmd', '05-Discussion.Rmd', '06-Conclusion.Rmd')} -->
<!-- ``` -->

<!-- Call the child documents -->
```{r body, child = c('./paper.rmd')}
